# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 22:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sowork_jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name=b'comment')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name=b'post_time')),
                ('job_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sowork_jobs.JobInfo', verbose_name=b'job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
