# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=100)),
                ('description', models.CharField(default='Description', max_length=500)),
                ('createTime', models.DateTimeField(editable=False)),
                ('lastUpdateTime', models.DateTimeField(editable=False)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
